#!/usr/bin/env bun
/**
 * Reads the version from package.json and writes src/version.ts
 * so all entry points share a single source of truth.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const content = `// Auto-generated by scripts/inject-version.ts — do not edit manually\nexport const VERSION = '${pkg.version}';\n`;

writeFileSync(join(root, 'src', 'version.ts'), content);
console.log(`  Injected VERSION = '${pkg.version}' into src/version.ts`);
